import { useEffect, useMemo, useRef, useState } from 'react'

/**
 * Multi-step clarification wizard — options are generated by the backend classifier,
 * not hardcoded in the UI.
 */
export default function ClarifyWizardCard({ data, onComplete, onSkip }) {
  const cardRef = useRef(null)
  useEffect(() => {
    cardRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' })
  }, [])

  const intro = data?.intro || 'A few quick questions so I route this correctly.'
  const steps = Array.isArray(data?.steps) ? data.steps : []
  const [stepIndex, setStepIndex] = useState(0)
  const [selections, setSelections] = useState({})

  const step = steps[stepIndex]
  const isLast = stepIndex >= steps.length - 1
  const currentSelected = step ? selections[step.id] || [] : []

  const totalSelected = useMemo(
    () => Object.values(selections).reduce((n, arr) => n + (arr?.length || 0), 0),
    [selections],
  )

  if (!steps.length) return null

  function toggleOption(optionId) {
    if (!step) return
    setSelections((prev) => {
      const cur = prev[step.id] || []
      if (step.multi) {
        const next = cur.includes(optionId) ? cur.filter((x) => x !== optionId) : [...cur, optionId]
        return { ...prev, [step.id]: next }
      }
      return { ...prev, [step.id]: [optionId] }
    })
  }

  function buildPayload() {
    return steps.map((s) => {
      const ids = selections[s.id] || []
      const labels = (s.options || [])
        .filter((o) => ids.includes(o.id))
        .map((o) => o.label)
      return { stepId: s.id, stepTitle: s.title, optionIds: ids, labels }
    })
  }

  function handleNext() {
    if (!currentSelected.length) return
    if (isLast) {
      onComplete?.(buildPayload())
      return
    }
    setStepIndex((i) => i + 1)
  }

  function handleBack() {
    setStepIndex((i) => Math.max(0, i - 1))
  }

  return (
    <div
      ref={cardRef}
      style={{
        border: '1px solid var(--border)',
        borderRadius: 12,
        overflow: 'hidden',
        maxWidth: 520,
        background: 'var(--surface)',
        boxShadow: '0 8px 24px rgba(42, 59, 124, 0.08)',
      }}
    >
      <div
        style={{
          padding: '12px 16px',
          borderBottom: '1px solid var(--border)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 12,
        }}
      >
        <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)', lineHeight: 1.4 }}>
          {step?.title || 'Clarify'}
        </div>
        <div style={{ fontSize: 11, color: 'var(--text-muted)', whiteSpace: 'nowrap' }}>
          {stepIndex + 1} of {steps.length}
        </div>
      </div>

      {stepIndex === 0 && intro && (
        <div style={{ padding: '10px 16px 0', fontSize: 12, color: 'var(--text-muted)', lineHeight: 1.5 }}>
          {intro}
        </div>
      )}

      <div style={{ padding: '10px 8px 8px' }}>
        {(step?.options || []).map((opt) => {
          const checked = currentSelected.includes(opt.id)
          return (
            <button
              key={opt.id}
              type="button"
              onClick={() => toggleOption(opt.id)}
              style={{
                display: 'flex',
                alignItems: 'flex-start',
                gap: 10,
                width: '100%',
                textAlign: 'left',
                padding: '10px 12px',
                marginBottom: 4,
                border: `1px solid ${checked ? 'var(--accent, #3E94A5)' : 'var(--border)'}`,
                borderRadius: 10,
                background: checked ? 'var(--accent-light, #edf7f9)' : 'var(--bg)',
                cursor: 'pointer',
                fontFamily: 'Inter, sans-serif',
              }}
            >
              <span
                style={{
                  width: 16,
                  height: 16,
                  borderRadius: step.multi ? 4 : '50%',
                  border: `2px solid ${checked ? 'var(--accent, #3E94A5)' : '#c9d2ea'}`,
                  background: checked ? 'var(--accent, #3E94A5)' : 'transparent',
                  flexShrink: 0,
                  marginTop: 2,
                }}
              />
              <span style={{ fontSize: 13, color: 'var(--text)', lineHeight: 1.45 }}>{opt.label}</span>
            </button>
          )
        })}
      </div>

      <div
        style={{
          padding: '10px 14px 12px',
          borderTop: '1px solid var(--border)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 8,
        }}
      >
        <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
          {totalSelected} selected
        </span>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {stepIndex > 0 && (
            <button type="button" className="sug-btn" onClick={handleBack}>
              Back
            </button>
          )}
          <button type="button" className="sug-btn" onClick={() => onSkip?.()}>
            Skip
          </button>
          <button
            type="button"
            className="sug-btn sug-btn--primary"
            disabled={!currentSelected.length}
            onClick={handleNext}
            title={isLast ? 'Continue' : 'Next'}
          >
            {isLast ? 'Continue' : '→'}
          </button>
        </div>
      </div>
    </div>
  )
}
